### ISSUE TITLE
Very large URL message DoS

### ISSUE THREAD

**Issue by superp00t** [Cryptodog/cryptodog#46]
Cryptodog allows incredibly long messages to be sent in a short period of time, still. Currently, someone is spamming the room `lobby` with 13000 character long URLs with the effect of crashing clients remotely. This takes advantage of [autolink.js](https://github.com/Cryptodog/cryptodog/blob/master/js/lib/autolink.js) not having **any** limit on URL size.

Additionally, even if I disable autolinking, and even if the offending bots are ignored, the client still suffers incredible performance decreases. 

The server should not relay extremely long messages, and the client should also impose a size limit on URLs before they are auto-linked.

**Comment by superp00t** [comment]
#40

**Comment by ayyghost** [comment]
Thanks for reporting. This issue was recently brought to my attention in private, and a patch is underway.

As you suggested, I'll be implementing server-side and client-side fixes; however, the problem primarily has to do with message size, not the auto-link feature. Spamming any sufficiently long message, URL or not, will degrade client performance to the point of crashing.
